version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/deploy
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: unbuntu
    group: unbuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: unbuntu
