chatgpt:
  api-key: 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

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maumdiary
    username: maum_admin
    password: maumdiary123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher