spring:
  datasource:
    url: jdbc:mysql://maumdiary-db.cjzfjqrjkdm5.ap-northeast-2.rds.amazonaws.com:3306/MaumDiaryDB
    username: MaumDiary_admin
    password: maumdiary123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: API-KEY

openai :
  api-key: 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

chat-gpt:
  api-key: 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
